version: "3.8"
services: 
    hadoop1:
        image: yangqinjiang/hadoop-alone:latest
        container_name: hadoop1
        hostname: hadoop1
        tty: true
        ports: # 暴露端口信息  - "宿主机端口:容器暴露端口"
            - "1570:50070" # 更换端口, windows 10有权限限制, 所以用1570
        networks: 
            fixed:
                ipv4_address: "172.21.0.2"
        deploy:
            resources:
                limits:
                    cpus: '0.5' 
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 1024M

    # zooKeeper 集群
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        hostname: zookeeper
        ports:
          - '2181:2181'
        deploy:
            resources:
                limits:
                    cpus: '0.5' 
                    memory: 128M
                reservations:
                    cpus: '0.5'
                    memory: 128M
        networks: 
            fixed:
                ipv4_address: "172.21.0.3"
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - ./zookeeper-persistence:/bitnami/zookeeper          
    # kafka
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        hostname: kafka
        ports:
            - '9092:9092'
        deploy:
            resources:
                limits:
                    cpus: '0.5' 
                    memory: 512M
                reservations:
                    cpus: '0.5'
                    memory: 512M
        networks: 
            fixed:
                ipv4_address: "172.21.0.4"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        volumes:
            - ./kafka-persistence/:/bitnami/kafka            
        depends_on:
            - zookeeper

#  elasticsearch:6.8.17        
    elasticsearch:
        image: 'elasticsearch:6.8.17'
        container_name: elasticsearch
        hostname: elasticsearch
        ports:
            - '1571:9200'
            - '1572:9300'
        deploy:
            resources:
                limits:
                    cpus: '0.5' 
                    memory: 512M
                reservations:
                    cpus: '0.5'
                    memory: 512M
        networks: 
            fixed:
                ipv4_address: "172.21.0.5"
        environment:
            - node.name=es01
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data
        depends_on:
            - hadoop1                
networks:
    fixed:
        ipam:
            driver: default
            config: 
                - subnet: "172.21.0.0/24"